/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import controlador.Lista;
import controlador.Nodo;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Vehiculo;
import util.Util;

/**
 *
 * @author ANDRES ROMERO
 */
public class VSalida extends javax.swing.JFrame {

    Lista listasencilla = new Lista();
    Nodo nodo1 = null;
    Vehiculo vehiculo = null;

    final String NOM_ARCHIVO_Lista = "lista.dat";
    util.Util util = new Util();
    ArrayList<Object> objetosLista = new ArrayList<>();

    final String NOM_ARCHIVO_VehiculosParqueados = "vehiculosParqueados.dat";
    ArrayList<Object> objetosVehiculos = new ArrayList<>();

    public VSalida() {
        initComponents();
        getObjetos();
        llenarCbxConPlacas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxPlacas = new javax.swing.JComboBox();
        txtCerrar = new javax.swing.JButton();
        txtAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido al parqueadero");

        jLabel2.setText("Seleccione la placa del vehiculo que va a retirar:");

        txtCerrar.setText("Cerrar");
        txtCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCerrarActionPerformed(evt);
            }
        });

        txtAceptar.setText("Aceptar");
        txtAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCerrar)
                    .addComponent(txtAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAceptarActionPerformed

        try {
            Vehiculo carro = listasencilla.crearObjetoSalida(nodo1);
            Controlador controlador = new Controlador();
            Date fechaSalida = new Date();

            carro.setCostoParqueo(controlador.costoTotal(carro.getFechaIngreso()));
            carro.setFechaSalida(fechaSalida);

            listasencilla.borrarVehiculo(nodo1);
            objetosLista.add(listasencilla);
            util.serializar(NOM_ARCHIVO_Lista, objetosLista);

            objetosVehiculos.add(carro);
            util.serializar(NOM_ARCHIVO_VehiculosParqueados, objetosVehiculos);

            Vparqueadero parqueadero = new Vparqueadero();
            parqueadero.setVisible(true);
            this.setVisible(false);
        } catch (ParseException ex) {
            Logger.getLogger(VSalida.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtAceptarActionPerformed

    private void txtCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCerrarActionPerformed
        Vparqueadero parqueadero = new Vparqueadero();
        parqueadero.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_txtCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VSalida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox cbxPlacas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton txtAceptar;
    private javax.swing.JButton txtCerrar;
    // End of variables declaration//GEN-END:variables

    public void getObjetos() {
        if (util.desSerializar(NOM_ARCHIVO_Lista) != null) {
            objetosLista = (ArrayList<Object>) util.desSerializar(NOM_ARCHIVO_Lista);
            listasencilla = (Lista) objetosLista.get(0);
            objetosLista.clear();
        }
        if (util.desSerializar(NOM_ARCHIVO_VehiculosParqueados) != null) {
            objetosVehiculos = (ArrayList<Object>) util.desSerializar(NOM_ARCHIVO_VehiculosParqueados);
        }
    }

    public void llenarCbxConPlacas() {
        for (int h = 0; h < listasencilla.placasVehiculosParqueados(nodo1).length; h++) {
            this.cbxPlacas.addItem(listasencilla.placasVehiculosParqueados(nodo1)[h]);
        }
    }

}
